export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const FETCH_BOOKS_FAILURE = "FETCH_BOOKS_FAILURE";
export const FETCH_BOOKS_PENDING = "FETCH_BOOKS_PENDING";

export const FETCH_BOOK_SUCCESS = "FETCH_BOOK_SUCCESS";
export const FETCH_BOOK_FAILURE = "FETCH_BOOK_FAILURE";
export const FETCH_BOOK_PENDING = "FETCH_BOOK_PENDING";

export const CREATE_BOOK_SUCCESS = "CREATE_BOOK_SUCCESS";
export const CREATE_BOOK_FAILURE = "CREATE_BOOK_FAILURE";
export const CREATE_BOOK_PENDING = "CREATE_BOOK_PENDING";

export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
export const DELETE_BOOK_FAILURE = "DELETE_BOOK_FAILURE";
export const DELETE_BOOK_PENDING = "DELETE_BOOK_PENDING";

export const EDIT_BOOK_SUCCESS = "EDIT_BOOK_SUCCESS";
export const EDIT_BOOK_FAILURE = "EDIT_BOOK_FAILURE";
export const EDIT_BOOK_PENDING = "EDIT_BOOK_PENDING";
