// User actions
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAILURE = "USER_REGISTRATION_FAILURE";
export const USER_REGISTRATION_PENDING = "USER_REGISTRATION_PENDING";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const USER_LOGIN_PENDING = "USER_LOGIN_PENDING";
export const USER_LOGOUT = "USER_LOGOUT";
